server:
  port: 8101
spring:
  application:
    name: eureka-client-security
eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://feichen:1234@localhost:8003/eureka #配置注册中心地址
