server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka
feign:
  circuitbreaker:
    enabled: true  # feign.hystrix.enabled 已废弃
  compression:
    request:
      enabled: false #是否对请求进行GZIP压缩
      mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
      min-request-size: 2048 #超过该大小的请求会被压缩
    response:
      enabled: true #是否对响应进行GZIP压缩
logging:
  level:
    root: info
